### ISSUE TITLE
In World, for-loop optimization.

### ISSUE THREAD

**Issue by usandfriends** [Carpetfizz/TrapEngine#1]
[World.java](https://github.com/Carpetfizz/TrapEngine/blob/master/engine/src/com/ajayramesh/TrapEngine/World.java), `for` loops recalculate the size of the entities before each loop execution. Consider saving the size as a variable and checking against that to optimize.

**Comment by usandfriends** [comment]
Even better: http://stackoverflow.com/questions/8426693/

**Comment by Carpetfizz** [comment]
Fixed, thanks! Interestingly, the decompiled class file outputs this:

```
    Iterator var1 = this.Entities.iterator();
    while(var1.hasNext()) {
        Entity e = (Entity)var1.next();
            if(e.enabled) {
                e.update(this.input);
             }
    }
```

Seems like the same efficiency as initializing the size before walking through it.
